"""add meeting processing status

Revision ID: 0c4c991acd51
Revises: 203960d25ba0
Create Date: 2026-08-10 14:14:34.089499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4c991acd51'
down_revision: Union[str, Sequence[str], None] = '203960d25ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "meetings",
        sa.Column(
            "processing_status",
            sa.String(length=30),
            nullable=False,
            server_default="COMPLETED",
        ),
    )

    op.add_column(
        "meetings",
        sa.Column(
            "processing_error",
            sa.Text(),
            nullable=True,
        ),
    )

    op.add_column(
        "meetings",
        sa.Column(
            "processing_started_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "meetings",
        sa.Column(
            "processing_finished_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "meetings",
        sa.Column(
            "processing_seconds",
            sa.Float(),
            nullable=True,
        ),
    )

    op.add_column(
        "meetings",
        sa.Column(
            "stored_file_path",
            sa.Text(),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_meetings_processing_status"),
        "meetings",
        ["processing_status"],
        unique=False,
    )

    op.alter_column(
        "meetings",
        "processing_status",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_processing_status'), table_name='meetings')
    op.drop_column('meetings', 'stored_file_path')
    op.drop_column('meetings', 'processing_seconds')
    op.drop_column('meetings', 'processing_finished_at')
    op.drop_column('meetings', 'processing_started_at')
    op.drop_column('meetings', 'processing_error')
    op.drop_column('meetings', 'processing_status')
    # ### end Alembic commands ###
